Ex12 js dom
qwelol/external-courses pull request #25
Opened 2018-11-18 17:17 UTC by qwelol

2018-11-19 15:06 UTC, DairoGrey requested changes

2018-11-19 15:06 UTC, DairoGrey commented on src/ex12_js-dom/task.js
> +  if(elem.childNodes[i].nodeType === 1)
Ненаглядное сравнение. Посмотри пример: https://developer.mozilla.org/ru/docs/Web/API/Node/nodeType

2018-11-19 15:06 UTC, DairoGrey commented on src/ex12_js-dom/task.js
> +	  if (elem.childNodes[i].localName in tags)
Два похожих блока. Надо отрефакторить в один.

2018-11-19 15:08 UTC, DairoGrey requested changes

2018-11-19 15:08 UTC, DairoGrey commented on src/ex12_js-dom/task.js
> +		  tags[elem.childNodes[i].localName]++;
Придерживайся одинакового форматирования для всех блоков.

2018-11-19 19:10 UTC, qwelol commented on src/ex12_js-dom/task.js
> +	  if (elem.childNodes[i].localName in tags)
Не могу понять, как это можно сделать. По сути, я же в цикле перебираю всех детей текущего узла. Для каждого дочернего элемента просматриваю и считаю все его классы:
```suggestion
 for (var j=0; j<elem.childNodes[i].classList.length; j++)
 {
  if (elem.childNodes[i].classList[j] in classes)
  {
   classes[elem.childNodes[i].classList[j]]++;	
  }
  else
  {
   classes[elem.childNodes[i].classList[j]]=1;	
  }
 }
```
потом учитываю сам элемент:
```suggestion
 if (elem.childNodes[i].localName in tags)
 {
  tags[elem.childNodes[i].localName]++;	
 }
 else
 {
  tags[elem.childNodes[i].localName]=1;
 }
```
 2 этих действия объединить в 1 без увеличения размера  кода у меня не получается.
Единственное, убрал проверку на непустой classList:
```suggestion
 if(!!elem.childNodes[i].classList)
```
потому что при пустом classList цикл просто не запустится и смысла от данной проверки нет

2018-11-22 15:40 UTC, DairoGrey commented on src/ex12_js-dom/task.js
> +	  if (elem.childNodes[i].localName in tags)
```
function increaseCounter(store, key) {
    if (key in store)
    {
        store[key]++;	
    }
    else
    {
        store[key]=1;	
    }
}

increaseCounter(classes, elem.childNodes[i].classList[j]);
```

2018-11-23 07:44 UTC, DairoGrey requested changes
Посмотри ответ на комментарий про похожие блоки кода

2018-11-24 18:24 UTC, qwelol commented on src/ex12_js-dom/task.js
> +	  if (elem.childNodes[i].localName in tags)
Это оказалось так просто, что я теперь чувствую себя тупеньким >_< 
Единственное, пришлось сделать так: 
`var storage=store;`
А то линтер ругается на изменение параметров функции

2018-11-25 08:17 UTC, DairoGrey approved these changes

2018-11-25 08:17 UTC, merged