Ex13 js events
qwelol/external-courses pull request #26
Opened 2018-11-19 12:16 UTC by qwelol

2018-11-19 15:11 UTC, DairoGrey requested changes

2018-11-19 15:11 UTC, DairoGrey commented on src/ex13_js-events/task.js
> +var openedDiv;
Форматирование файла. В редакторах есть горячие клавиши для этого и форматирование по сохранению.

2018-11-19 15:11 UTC, DairoGrey commented on src/ex13_js-events/task.js
> +		  openedDiv.parentNode.children[i].classList.remove('open');
Если изменится структура в HTML, надо будет менять код.

2018-11-19 19:53 UTC, qwelol commented on src/ex13_js-events/task.js
> +		  openedDiv.parentNode.children[i].classList.remove('open');
В каком плане изменится структура в HTML? 
Просто увеличение количества пунктов меню/содержимого меню проходит вполне безболезненно. Или в меню могут добавится элементы, которые не требуется скрывать?

2018-11-25 08:26 UTC, DairoGrey requested changes

2018-11-25 08:26 UTC, DairoGrey commented on src/ex13_js-events/task.js
> +		openedItem=node.parentNode;
Все равно осталась завязка на структуру HTML-разметки. От этого можно избавиться, назначив класс элементу списка, чтобы в дальнейшем искать уже по нему, а не жестко выбирая родителя.

2018-11-28 15:10 UTC, DairoGrey requested changes

2018-11-28 15:10 UTC, DairoGrey commented on src/ex13_js-events/task.js
> +		if (openedItem !== target.parentNode)
Вместо **parentNode** лучше использовать метод **closest**

2018-12-02 11:03 UTC, DairoGrey requested changes

2018-12-02 11:03 UTC, DairoGrey commented on src/ex13_js-events/task.js
> +		if (openedItem !== target.parentNode)
А это?

2018-12-03 12:33 UTC, qwelol commented on src/ex13_js-events/task.js
> +		if (openedItem !== target.parentNode)
Виноват

2018-12-03 17:55 UTC, DairoGrey approved these changes

2018-12-03 17:55 UTC, merged